sudo: required
services:
  - docker
  
before_install:
  - docker build -t stephengrinder/docker-react -f Dockerfile.dev .
  
script:
  - docker run stephengrinder/docker-react npm run test -- --coverage
